#springboot port
server:
  port: 9001

#es & redis
spring:
  data:
    redis:
      host: 112.35.176.43
      port: 9500
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
elasticsearch:
  host: 112.35.176.43
  port: 9201

timerQueue:
  name: TIMER_TASK

#线程池配置参数
thread-pool:
  core-size: 5            # 核心线程数
  max-size: 10            # 最大线程数
  queue-capacity: 50      # 队列容量
  keep-alive-time: 30    # 线程的最大空闲时间（秒）
  thread-name-prefix: emailThreadPool

#rocketmq
rocketmq:
  name-server: 112.35.176.43:9876
  producer:
    group: email-producer


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
